{{- if .Values.cluster.objectStore.enabled }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Values.cluster.objectStore.name | default (printf "%s-object-store" (include "cluster.fullname" .)) }}
  namespace: {{ include "cluster.namespace" . }}
spec:
  retentionPolicy: {{ .Values.cluster.objectStore.retentionPolicy }}
  {{- with .Values.cluster.objectStore.instanceSidecarConfiguration }}
  instanceSidecarConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  configuration:
    {{- toYaml .Values.cluster.objectStore.configuration | nindent 4 }}
{{- end }}
